use_frameworks!

target 'BaseClassLibrary_Example' do
  pod 'BaseClassLibrary', :path => '../'

  target 'BaseClassLibrary_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
